
# @file .travis.yml
# @authors Vivek Sood and Charu Sharma
# @brief yml for travis build
# @date 2021-10-05
# @copyright Copyright (c) 2021

# ENPM808X Midterm - Phase 0 Proposal


dist: xenial

language: cpp

matrix:
  include:
    - os: linux
      compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - george-edison55-precise-backports
          packages:
            - g++-5
            - cmake
            - cmake-data
      env: COMPILER=g++-5

before_install:
  - pip install --user cpp-coveralls
install:
  - sudo apt-get install -y -qq lcov
script:
  - export CXX=$COMPILER;
  - mkdir build
  - cd build
  - cmake -DCOVERAGE=ON -DCMAKE_BUILD_TYPE=Debug ../
  - make
  - make code_coverage
  - test/cpp-test

after_success:
  - coveralls --root .. -E ".*external.*" -E ".*CMakeFiles.*" -E ".*test/.*.cpp.*"

notifications:
  email:
    recipients:
      - viveksood257@gmail.com

